apiVersion: v1
kind: Service
metadata:
  name: samba-ad
  namespace: core
  labels:
    app: samba-ad
spec:
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: ldap
      port: 389
      protocol: TCP
    - name: ldaps
      port: 636
      protocol: TCP
    - name: krb5
      port: 88
      protocol: TCP
    - name: krb5-udp
      port: 88
      protocol: UDP
    - name: smb
      port: 445
      protocol: TCP
  selector:
    app: samba-ad
  clusterIP: None # Headless service for StatefulSet identity

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: samba-ad
  namespace: core
spec:
  selector:
    matchLabels:
      app: samba-ad
  serviceName: "samba-ad"
  replicas: 1 # AD uses multi-master replication, but starting with 1 to bootstrap
  template:
    metadata:
      labels:
        app: samba-ad
    spec:
      containers:
        - name: samba-ad
          image: nowsci/samba-domain:latest # Example image, arguably should be built in-house for sovereignty
          securityContext:
            capabilities:
              add: ["NET_ADMIN"] # Required for AD functioning
          env:
            - name: DOMAIN
              value: "INTERNAL.SOVEREIGN.LAN" # Change this
            - name: REALM
              value: "INTERNAL.SOVEREIGN.LAN"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: samba-secrets
                  key: admin-password
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 389
              name: ldap
              protocol: TCP
            - containerPort: 636
              name: ldaps
              protocol: TCP
            - containerPort: 88
              name: krb5
              protocol: TCP
            - containerPort: 88
              name: krb5-udp
              protocol: UDP
            - containerPort: 445
              name: smb
              protocol: TCP
          volumeMounts:
            - name: samba-data
              mountPath: /var/lib/samba
  volumeClaimTemplates:
    - metadata:
      name: samba-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
